module.exports = {
    extends: 'airbnb',
    parser: 'babel-eslint',
    plugins: ['jest', 'compat', 'react-hooks'],
    env: {
        node: true,
        jest: true,
        browser: true,
    },
    rules: {
        strict: [0, 'global'],
        indent: [1, 'tab', {SwitchCase: 1, VariableDeclarator: 1}],
        'no-tabs': 0,
        'no-plusplus': 0,
        'arrow-body-style': [1, 'as-needed'],
        'arrow-parens': [2, 'as-needed', {requireForBlockBody: true}],
        'no-console': [1, {allow: ['warn']}],
        'max-len': [
            2,
            120,
            2,
            {
                ignoreUrls: true,
                ignoreComments: false,
            },
        ],
        'no-underscore-dangle': [
            'error',
            {
                allow: ['_id', '_index', '_score', '_shards', '_source', '_type', '_state', '_embedded'],
                allowAfterThis: true,
                allowAfterSuper: true,
            },
        ],
        'import/no-extraneous-dependencies': ['warn', {devDependencies: true}],
        'import/no-unresolved': ['error', {caseSensitive: false}],
        'import/named': 2,
        'import/prefer-default-export': 0,
        'no-restricted-syntax': ['error', 'ForInStatement', 'LabeledStatement', 'WithStatement'],
        'no-await-in-loop': 0,
        'no-unused-vars': ['warn', {vars: 'local', args: 'after-used', ignoreRestSiblings: true}],
        'react/jsx-indent-props': [2, 'tab'],
        'react/jsx-indent': [2, 'tab'],
        'compat/compat': 2,
        'jest/no-disabled-tests': 'warn',
        'jest/no-focused-tests': 'error',
        'jest/no-identical-title': 'error',
        'jest/valid-expect': 'error',
        'prefer-destructuring': 0,
        'react/no-unused-state': 'warn',
        'react/jsx-handler-names': 'warn',
        'react-hooks/rules-of-hooks': 'error',
    },
    settings: {
        polyfills: ['fetch'],
        compiler: 'babel',
    },
};
